// src/adapters/polymarket-deposit-wallet.test.ts
// LOCKS the hand-ported UUPS deposit-wallet derivation to the OFFICIAL SDK's exact
// output. The expected addresses were generated by running
// @polymarket/builder-relayer-client's deriveDepositWallet(eoa, factory, impl) in
// the PolyNews tree (where the SDK is installed) — so if our viem port drifts a
// single byte from the SDK, these fail. This is the byte-exact lock that lets the
// MCP keep the SDK out of its prod dep tree without hand-rolling crypto blind.
import { test } from "node:test";
import assert from "node:assert/strict";
import {
  deriveDepositWalletUUPS,
  initCodeHashERC1967,
  isBeaconResult,
  assertUUPSFactory,
  DEPOSIT_WALLET_FACTORY,
  DEPOSIT_WALLET_IMPLEMENTATION,
} from "./polymarket-deposit-wallet.js";
import type { Hex } from "viem";

// (EOA owner) -> (deposit wallet) — verbatim from the SDK deriveDepositWallet().
const SDK_VECTORS: ReadonlyArray<readonly [Hex, Hex]> = [
  ["0xA6350f11AF9Bd54603EDaB09871737539c35D0e0", "0x648dDfB3b6338Ba33cCD413042764D1B72Fb7951"],
  ["0x0000000000000000000000000000000000000001", "0x57ffBc34De23124fAeb8387fcd689d314E57aCcD"],
  ["0x92C0d39f947d371bC9a8323ce3f110ab4663eFFD", "0x24f1036FE0ae555b3EF81fe0b43d024033BD4f07"],
];

for (const [eoa, expected] of SDK_VECTORS) {
  test(`deriveDepositWalletUUPS matches the SDK vector for ${eoa}`, () => {
    assert.equal(deriveDepositWalletUUPS(eoa), expected); // checksummed exact match
  });
}

test("derivation uses the SDK-config factory + UUPS implementation", () => {
  assert.equal(DEPOSIT_WALLET_FACTORY, "0x00000000000Fb5C9ADea0298D729A0CB3823Cc07");
  assert.equal(DEPOSIT_WALLET_IMPLEMENTATION, "0x58CA52ebe0DadfdF531Cde7062e76746de4Db1eB");
});

test("initCodeHashERC1967 is deterministic + 32 bytes", () => {
  const args = "0x" + "00".repeat(64);
  const h1 = initCodeHashERC1967(DEPOSIT_WALLET_IMPLEMENTATION, args as Hex);
  const h2 = initCodeHashERC1967(DEPOSIT_WALLET_IMPLEMENTATION, args as Hex);
  assert.equal(h1, h2);
  assert.equal(h1.length, 66); // 0x + 32 bytes
});

test("isBeaconResult: zero/empty => UUPS, non-zero word => beacon", () => {
  assert.equal(isBeaconResult("0x"), false);
  assert.equal(isBeaconResult("0x" + "0".repeat(64)), false);
  assert.equal(isBeaconResult("0x" + "0".repeat(24) + "1".repeat(40)), true);
});

test("assertUUPSFactory: passes on revert/zero, THROWS on a real beacon", async () => {
  await assertUUPSFactory(async () => {
    throw new Error("execution reverted");
  }); // revert => UUPS => no throw
  await assertUUPSFactory(async () => "0x" + "0".repeat(64)); // zero => UUPS => no throw
  await assert.rejects(
    () => assertUUPSFactory(async () => "0x" + "0".repeat(24) + "ab".repeat(20)),
    /BeaconProxy now, not/,
  );
});
