// src/adapters/polymarket-deposit-wallet.test.ts
// LOCKS the hand-ported UUPS deposit-wallet derivation to the OFFICIAL SDK's exact
// output. The expected addresses were generated by running
// @polymarket/builder-relayer-client's deriveDepositWallet(eoa, factory, impl) in
// the PolyNews tree (where the SDK is installed) — so if our viem port drifts a
// single byte from the SDK, these fail. This is the byte-exact lock that lets the
// MCP keep the SDK out of its prod dep tree without hand-rolling crypto blind.
import { test } from "node:test";
import assert from "node:assert/strict";
import {
  deriveDepositWalletUUPS,
  initCodeHashERC1967,
  isBeaconResult,
  assertUUPSFactory,
  signPoly1271Order,
  type Poly1271Order,
  DEPOSIT_WALLET_FACTORY,
  DEPOSIT_WALLET_IMPLEMENTATION,
} from "./polymarket-deposit-wallet.js";
import { getAddress, hexToBytes, type Hex } from "viem";
import { makeEvmSigner } from "../signers/evm.js";

// (EOA owner) -> (deposit wallet) — verbatim from the SDK deriveDepositWallet().
const SDK_VECTORS: ReadonlyArray<readonly [Hex, Hex]> = [
  ["0xA6350f11AF9Bd54603EDaB09871737539c35D0e0", "0x648dDfB3b6338Ba33cCD413042764D1B72Fb7951"],
  ["0x0000000000000000000000000000000000000001", "0x57ffBc34De23124fAeb8387fcd689d314E57aCcD"],
  ["0x92C0d39f947d371bC9a8323ce3f110ab4663eFFD", "0x24f1036FE0ae555b3EF81fe0b43d024033BD4f07"],
];

for (const [eoa, expected] of SDK_VECTORS) {
  test(`deriveDepositWalletUUPS matches the SDK vector for ${eoa}`, () => {
    assert.equal(deriveDepositWalletUUPS(eoa), expected); // checksummed exact match
  });
}

test("derivation uses the SDK-config factory + UUPS implementation", () => {
  assert.equal(DEPOSIT_WALLET_FACTORY, "0x00000000000Fb5C9ADea0298D729A0CB3823Cc07");
  assert.equal(DEPOSIT_WALLET_IMPLEMENTATION, "0x58CA52ebe0DadfdF531Cde7062e76746de4Db1eB");
});

test("initCodeHashERC1967 is deterministic + 32 bytes", () => {
  const args = "0x" + "00".repeat(64);
  const h1 = initCodeHashERC1967(DEPOSIT_WALLET_IMPLEMENTATION, args as Hex);
  const h2 = initCodeHashERC1967(DEPOSIT_WALLET_IMPLEMENTATION, args as Hex);
  assert.equal(h1, h2);
  assert.equal(h1.length, 66); // 0x + 32 bytes
});

test("isBeaconResult: zero/empty => UUPS, non-zero word => beacon", () => {
  assert.equal(isBeaconResult("0x"), false);
  assert.equal(isBeaconResult("0x" + "0".repeat(64)), false);
  assert.equal(isBeaconResult("0x" + "0".repeat(24) + "1".repeat(40)), true);
});

test("assertUUPSFactory: passes on revert/zero, THROWS on a real beacon", async () => {
  await assertUUPSFactory(async () => {
    throw new Error("execution reverted");
  }); // revert => UUPS => no throw
  await assertUUPSFactory(async () => "0x" + "0".repeat(64)); // zero => UUPS => no throw
  await assert.rejects(
    () => assertUUPSFactory(async () => "0x" + "0".repeat(24) + "ab".repeat(20)),
    /BeaconProxy now, not/,
  );
});

// ── POLY_1271 (ERC-7739) signing — locked to the SDK vector ─────────────────
// Fixed test key 0x11..11; the EOA + deposit wallet + signature were generated by
// the REAL clob-client-v2 inner-sig primitive (viem walletClient.signTypedData) over
// the documented buildOrderSignature construction. If our hashTypedData + @noble
// signer drift one byte from the SDK, this fails.
const TEST_KEY = hexToBytes(("0x" + "11".repeat(32)) as Hex);
const TEST_EOA = "0x19E7E376E7C213B7E7e7e46cc70A5dD086DAff2A";
const TEST_DW = "0x7a57144fAfde87F5cE4a880D570BAe58eeBC83f2";
const VECTOR_SIG =
  "0x3346a9716fa21e98185e8e9bdbf1ad3379c9b33020e89fb2e8a9951b442ea3a4237b6228743248efdf5955ab4bbec83ddcb47ace570ea27ffd45bbe4dcf2ed881b3264e159346253e26a64e00b69032db0e7d32f94628de3e6eecb50304d7af3d26269965347e761506188d8f5a2ae49bb1499409b9d037088e12566db51cfc12b4f726465722875696e743235362073616c742c61646472657373206d616b65722c61646472657373207369676e65722c75696e7432353620746f6b656e49642c75696e74323536206d616b6572416d6f756e742c75696e743235362074616b6572416d6f756e742c75696e743820736964652c75696e7438207369676e6174757265547970652c75696e743235362074696d657374616d702c62797465733332206d657461646174612c62797465733332206275696c6465722900ba";

test("fixed key derives the SDK's EOA + deposit wallet (ties signing to derivation)", () => {
  const signer = makeEvmSigner(TEST_KEY);
  assert.equal(getAddress(signer.address), getAddress(TEST_EOA));
  assert.equal(deriveDepositWalletUUPS(getAddress(TEST_EOA)), getAddress(TEST_DW));
});

test("signPoly1271Order matches the SDK ERC-7739 vector byte-for-byte", () => {
  const signer = makeEvmSigner(TEST_KEY);
  const order: Poly1271Order = {
    salt: "479249096012",
    maker: getAddress(TEST_DW),
    signer: getAddress(TEST_DW),
    tokenId: "123456789",
    makerAmount: "1000000",
    takerAmount: "2000000",
    side: 0,
    signatureType: 3,
    timestamp: "1700000000000",
    metadata: `0x${"00".repeat(32)}`,
    builder: `0x${"00".repeat(32)}`,
  };
  const sig = signPoly1271Order({
    signer,
    order,
    domain: { exchange: "0xE111180000d2663C0091e4f400237545B87B996B", chainId: 137, name: "Polymarket CTF Exchange", version: "2" },
  });
  assert.equal(sig, VECTOR_SIG);
});
